fix/configure access according to permissions
energywebfoundation/origin pull request #1471
Opened 2020-09-02 11:33 UTC by alexworker23

Сonfigure access according to permissions

2020-09-02 14:12 UTC, JGiter requested changes

2020-09-02 14:12 UTC, JGiter commented on packages/origin-ui-core/src/components/Organization/Organization.tsx
> +        user?.organization?.id && isRole(user, Role.OrganizationAdmin) ? true : invitations.length;
Make showInvitations boolean
Invitations shouldn't be visible to anyone except Organization Admin

2020-09-02 14:12 UTC, JGiter commented on packages/origin-ui-core/src/components/Organization/Organization.tsx
> +            show: organization || irecAccount
Should be shown if exists organization and no irec

2020-09-02 14:12 UTC, JGiter commented on packages/origin-ui-core/src/components/certificates/Certificates.tsx
> +    const roleCheck = () =>
The function checking role should return false if the user is not in the organization. Therefore if in such case isRole returns true then instead of checking role in each component, it is better to do this check in the isRole function
Also roleCheck is too vague name

2020-09-02 14:12 UTC, JGiter commented on packages/origin-ui-core/src/components/certificates/Certificates.tsx
> +            show: isIssuer || roleCheck(),
Shouldn't inbox be hidden from issuer?

2020-09-02 14:12 UTC, JGiter commented on packages/origin-ui-core/src/components/devices/Device.tsx
> +            show: isRole(userOffchain, Role.Issuer)
Isn't this a duplication with roles?

2020-09-02 14:12 UTC, JGiter commented on packages/origin-ui-core/src/components/devices/Device.tsx
> +            show: roleCheck()
Isn't this a duplication with roles?

2020-09-02 14:26 UTC, alexworker23 commented on packages/origin-ui-core/src/components/Organization/Organization.tsx
> +        user?.organization?.id && isRole(user, Role.OrganizationAdmin) ? true : invitations.length;
Ok

2020-09-02 14:26 UTC, alexworker23 commented on packages/origin-ui-core/src/components/Organization/Organization.tsx
> +            show: organization || irecAccount
Ok

2020-09-02 14:34 UTC, alexworker23 commented on packages/origin-ui-core/src/components/certificates/Certificates.tsx
> +            show: isIssuer || roleCheck(),
Done

2020-09-04 07:54 UTC, JGiter approved these changes

2020-09-04 08:11 UTC, JosephBagaric approved these changes

2020-09-04 09:07 UTC, merged