feat(issuer-api): added validation to "to" address
energywebfoundation/origin pull request #1825
Opened 2020-12-21 12:10 UTC by ioncreature

Certification request creation "to" address

Certificate request has weak validation and when you send to: "" then it passes but mints to a caller instead of the user account. Since we want to support different send destination types like strings, eth addresses, etc, we should not add @IsEthereumAddress to the validation.

Instead, we should add an @IsNotEmpty() check to the to field in CreateCertificationRequestDTO .

In the CreateCertificationRequestHandler we should then check if this string is an Ethereum address before proceeding with the creation.

2020-12-21 13:18 UTC, JosephBagaric requested changes

2020-12-21 13:18 UTC, JosephBagaric commented on packages/issuer-api/src/pods/certification-request/handlers/create-certification-request.handler.ts
> +        if (!isValidEthereumAddress(to)) {
Please use the latest `ethers.utils.isAddress()`from the `ethers` package instead of a custom function, to avoid errors.

2020-12-21 13:42 UTC, JosephBagaric commented on packages/issuer-api/src/pods/certification-request/handlers/create-certification-request.handler.ts
> +const eth = /^(0x)[0-9a-f]{40}$/i;
This implementation assumes that `a-f` are always lower-case, which is not true for checksummed addresses. Sometimes they are also `A-F`.

2020-12-21 13:46 UTC, JosephBagaric commented
Please also add the following tests:
- Test that passes when a checksummed address is passed
- Test that passes when a "lowercased" address is passed
- (Optional) Test that passes when a "uppercased" address is passed

2020-12-21 13:47 UTC, JosephBagaric commented
IMO we should then only store the checksummed address in the backend, and work with checksummed addresses thereafter.

2020-12-21 14:24 UTC, JosephBagaric commented on packages/issuer-api/src/pods/certification-request/handlers/create-certification-request.handler.ts
> +        if (!isValidEthereumAddress(to)) {
Hmm ethers seems to return `false` for a non-checksummed address...

2020-12-21 14:42 UTC, JosephBagaric commented on packages/issuer-api/src/pods/certification-request/handlers/create-certification-request.handler.ts
> +        if (!isValidEthereumAddress(to)) {
No need for this, so long as it passes the tests.

2020-12-22 13:42 UTC, ioncreature commented
> IMO we should then cast the address to checksummed, and only store the checksummed address in the backend, and work with checksummed addresses thereafter.

Added checksum address saving

2020-12-22 13:42 UTC, ioncreature commented
> Please add the following tests:
> 
> * Test that passes when a checksummed address is passed (e.g. `0xD173313A51f8fc37BcF67569b463abd89d81844f`)
> * Test that passes when a "lowercased" address is passed (e.g. `0xd173313a51f8fc37bcf67569b463abd89d81844f`)

Done

2020-12-23 10:35 UTC, JosephBagaric approved these changes

2020-12-23 10:44 UTC, merged