Multi-owner private certificatesa
energywebfoundation/origin pull request #708
Opened 2020-03-19 14:38 UTC by JosephBagaric

2020-03-24 18:16 UTC, e00dan approved these changes

2020-03-25 09:04 UTC, kosecki123 commented on packages/origin-backend/src/pods/certificate/certificate.controller.ts
> +    @Get('/:id')
Should use auth system to authenticate user and allow only users commitments to be served.

2020-03-25 09:41 UTC, kosecki123 requested changes
LGTM but there are not a single test for this code. I think this should be tested thoroughly.

2020-03-25 09:53 UTC, JosephBagaric commented
> LGTM but there are not a single test for this code. I think this should be tested thoroughly.

Sure, there are old tests which pass - but will add new tests to cover more cases.

2020-03-25 10:05 UTC, kosecki123 approved these changes

2020-03-25 10:32 UTC, merged